# workflows/build-and-test-sdl.yml
#
# Build & Test Fractal SDL
# Build and test the internal Fractal version of SDL.

name: "Build & Test Fractal SDL"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build-and-test-fractal-sdl:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        config:
          - name: "Build and Publish Fractal SDL on Windows"
            os: windows-2016
          - name: "Build and Publish Fractal SDL on macOS"
            os: macos-10.14
          - name: "Build and Publish Fractal SDL on Linux Ubuntu"
            os: ubuntu-18.04

    env:
      binary-location: build

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: On Windows, Set up Visual Studio Developer Command Prompt (for nmake)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: On Linux, Install ALSA Audio Library
        if: runner.os == 'Linux'
        shell: bash
        run: sudo apt-get install libasound2-dev

      - name: Build Fractal SDL on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          REM create build output folder
          mkdir ${{ env.binary-location }}

          REM configure Cmake
          cmake ^
            -S . ^
            -B build ^
            -D HAVE_LIBC=ON ^
            -D DIRECTX=OFF ^
            -D CMAKE_BUILD_TYPE=Release ^
            -G "NMake Makefiles"

          REM build SDL
          cd ${{ env.binary-location }} && nmake SDL2-static

      - name: Build Fractal SDL on macOS
        if: runner.os == 'macOS'
        env:
            FRACTAL_OSX_SYSROOT: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk" # Necessary for building on macOS (protocol does NOT support 10.15+ SDKs)
        shell: bash
        run: |
          # Explicitly retrieve macOS 10.14 SDK
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.14.sdk.tar.xz

          # Untar it
          xz -d MacOSX10.14.sdk.tar.xz
          tar -xf MacOSX10.14.sdk.tar

          # Move it to the right folder for building SDL
          mv MacOSX10.14.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs

          # create build output folder
          mkdir ${{ env.binary-location }}

          # configure Cmake
          cmake \
            -S . \
            -B build \
            -D CMAKE_BUILD_TYPE=Release

          # build SDL
          cd ${{ env.binary-location }} && make SDL2-static

      - name: Build Fractal SDL on Linux Ubuntu
        if: runner.os == 'Linux'
        shell: bash
        run: |
          # create build output folder
          mkdir ${{ env.binary-location }}

          # configure Cmake
          cmake \
            -S . \
            -B build \
            -D CMAKE_BUILD_TYPE=Release

          # build SDL
          cd ${{ env.binary-location }} && make SDL2-static
